### ISSUE TITLE
Tagger crashes when attempting to write tags to file in Downloads folder

### ISSUE THREAD

**Issue by davidskeck** [NickvisionApps/Tagger#107]
Hello,

I'm using the latest version of Tagger ([V2023.7.0](https://github.com/NickvisionApps/Tagger/releases/tag/2023.7.0)), and it crashes when I try to write a tag to a file in the Downloads folder. I do have it installed as a Flatpak, but the previous version wrote the tags to this file without issue. I tested this by downgrading to the previous version and have no issues. Additionally, I set permissions in Flatseal to entire file system for the latest version and it still crashes.

```sh
user@laptop:~$ flatpak run org.nickvision.tagger 
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/run/user/1000/doc/1373cf18/dl/episode-11.mp3' is denied.
 ---> System.IO.IOException: Permission denied
```

**Comment by nlogozzo** [comment]
Maybe we need home access after all?
Weird that Flatseal didn't fix it.. 

@fsobolev

**Comment by fsobolev** [comment]
> Maybe we need home access after all? Weird that Flatseal didn't fix it..
> 
> @fsobolev

Can't reproduce this, for me Tagger open folders though portals as expected, and I can edit tags succesfully.

> Unhandled exception. System.UnauthorizedAccessException: Access to the path '/run/user/1000/doc/1373cf18/dl/episode-11.mp3' is denied.

The path indicates that the app still tries to access a folder opened through portal. After enabling home permission, restart the app and re-select the folder, you will see `/home/...` path in header instead of `/run/user/...`, and try again.

**Comment by nlogozzo** [comment]
Ah yes, if you've used Tagger in the past (V2022.11.x) you'll probably need to reselect the save folder too since we took away home permissions, no?

**Comment by fsobolev** [comment]
> Ah yes, if you've used Tagger in the past (V2022.11.x) you'll probably need to reselect the save folder too since we took away home permissions, no?

It just don't open any folder on start if it can't access the folder, so it's not the issue.

**Comment by nlogozzo** [comment]
> It just don't open any folder on start if it can't access the folder, so it's not the issue.

Ah true true

**Comment by davidskeck** [comment]
This is fixed by selecting "All user files" in Flatseal and then restarting Tagger. I'm not clear on why it didn't work the first time. Thanks!
