### ISSUE TITLE
Fuzzy Searching

### ISSUE THREAD

**Issue by dominikheinz** [NickvisionApps/Tagger#169]
**Summary:**

Currently it is possible to search for specific properties, like title, artist, year and so on.
We can search for an exact match, e.g. with `!artist="Lorna Shore"`.
I think it would be good if we can also perform a fuzzy search or sub-string search, similar to how [fzf](https://github.com/junegunn/fzf) works
For example, it would be nice if the artist `Lorna Shore` would also show up for queries like:
- `Lorna`
- `LShore`
- `shore` (case-insensitive)
- `Sho`

**Why?**

I think this would be especially useful if a field contains special characters/accents that I might not have on my keyboard, so searching for part of the value would be sufficient. 
Also, it would allow for listing of similar items, e.g. performing a search like `!genre="death"` could list:
- Death Metal
- Deathcore
- Blackened Deathcore
- Melodic Death Metal

etc etc.

**Comment by nlogozzo** [comment]
Should be simple to implement...just change == to Contains() when searching...

**Comment by nlogozzo** [comment]
True...i'll look for a true fuzzy search implementation

**Comment by nlogozzo** [comment]
> True...i'll look for a true fuzzy search implementation

@fsobolev thanks!!

**Comment by nlogozzo** [comment]
![Screenshot from 2023-07-25 22-47-51](https://github.com/NickvisionApps/Tagger/assets/17648453/d9d8528b-959f-4ba7-9101-480f20137c4c)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.7.1-rc1

**Comment by nlogozzo** [comment]
Please test the beta and let me know if the search covers your use cases :)
