### ISSUE TITLE
Crashes when applying changes

### ISSUE THREAD

**Issue by Zenihalt** [NickvisionApps/Tagger#173]
Whenever I select a track and add album art and apply the changes, the app crashes and the changes I just made didn't work.

For info, I am using Pop!_OS 22.04 LTS

Thank you for addressing my problem.

**Comment by nlogozzo** [comment]
Can you run the app in the terminal (flatpak run org.nickvision.tagger) and paste any error messages here?

Probably #146

CC @fsobolev

**Comment by nlogozzo** [comment]
See #174. Please reopen if this didn't fix your issue.
