### ISSUE TITLE
[Enhancement] Disable "Apply" button for unchanged files

### ISSUE THREAD

**Issue by jrom99** [NickvisionApps/Tagger#205]
When you open a file, the "Apply" button is always available, even if no changes are manually made or if there is no autommatic change to save. It would be better if the button was in the disabled state in such cases, similar to when you have no file selected.

Any file selected, even if unchanged:
![image](https://github.com/NickvisionApps/Tagger/assets/47498278/920e77c8-75c2-42d6-8930-8fa2b2ba390b)

No file selected:
![image](https://github.com/NickvisionApps/Tagger/assets/47498278/4e14dcfb-4bf0-4c23-aa66-c10d0651c102)

## System information

Tagger version: 2023.8.0 (from Flathub)
OS version: Ubuntu 23.04
Session type: wayland

**Comment by nlogozzo** [comment]
Self note: On implementing this, I'd like to use Aura.NetworkManager to enable/disable web services actions depending on network connectivity

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.8.1
