### ISSUE TITLE
Crash when performing advanced search for artist

### ISSUE THREAD

**Issue by jrom99** [NickvisionApps/Tagger#206]
## Describe the bug

Tagger crashes when performing advanced search for an artist's name.

## Screenshots/Video

[Screencast from 2023-08-02 14-25-47.webm](https://github.com/NickvisionApps/Tagger/assets/47498278/58db3ec1-0a44-4943-8d5f-d5fa7889a978)
[Screencast from 2023-08-02 14-27-28.webm](https://github.com/NickvisionApps/Tagger/assets/47498278/fba01f27-d89f-4616-80f9-d8599f2ffb99)

## System information

Tagger version: 2023.8.0 (from flathub)
OS: Ubuntu 23.04
Session type: wayland

## Additional context

[tagger_debug.txt](https://github.com/NickvisionApps/Tagger/files/12243011/tagger_debug.txt)

Crash log:
```
UnhandledException - unhandled exception: System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at NickvisionTagger.Shared.Controllers.MainWindowController.<>c__DisplayClass83_0.<AdvancedSearch>b__0(String a, String b) in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Controllers/MainWindowController.cs:line 1232
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at NickvisionTagger.Shared.Controllers.MainWindowController.AdvancedSearch(String s) in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Controllers/MainWindowController.cs:line 1232
   at NickvisionTagger.GNOME.Views.MainWindow.SearchChanged(SearchEntry sender, EventArgs e) in /run/build/org.nickvision.tagger/NickvisionTagger.GNOME/Views/MainWindow.cs:line 1124
   at GObject.Signal`1.<>c__DisplayClass11_0.<Connect>b__0(Value returnValue, Value[] parameters)
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, ValueData[] paramValuesData, IntPtr invocationHint, IntPtr userData)
```

**Comment by nlogozzo** [comment]
@jrom99 Can you download and install the file (`
org.nickvision.tagger-x86_64`) from the `Artifacts` section here: https://github.com/NickvisionApps/Tagger/actions/runs/5742673637 and see if it's fixed.

Once you extract the zip, you'll see a `.flatpak` file. You can install and run it via:
```
flatpak install org.nickvision.tagger.flatpak
flatpak run org.nickvision.tagger//master
```

*You can later uninstall it via `flatpak uninstall org.nickvision.tagger//master`*

**Comment by nlogozzo** [comment]
What's `TP`, `FP`, `FN`? Keyboard layouts?

Starting with V2023.7.1, the algorithm we use for advances search is a `fuzzy search`. So it's not false positive and false negatives that you are seeing but files that some what matched what you typed.

`fé` obvsiously matches, `flo` matches because its just `félo` without the `é`, etc...

**Comment by jrom99** [comment]
TP is True Positive, FP is False Positive, FN is False Negative. Terms such as `flow` and `flm` should not match the string "Féloche", but currently do. Meanwhile, `fe` and `fl` should match, but currently do not.

**Comment by fsobolev** [comment]
> Terms such as `flow` and `flm` should not match the string "Féloche", but currently do. Meanwhile, `fe` and `fl` should match, but currently do not.

`flow` and `flm` are closer to the result by length and so by matching ratio. The purpose of fuzzy search is to help find things in case of typos, mistakes or a couple of missing symbols, and with current configuration it does the job well enough, it's not worth wasting time on adjusting to minimize "false positives".

**Comment by nlogozzo** [comment]
`fe` probably doesn't match `Fé` because the e's although may be the same to us....they're completely different characters and thus Fuzzy search probably thinks they're not close.

https://github.com/JakeBayer/FuzzySharp is the library we use...feel free to open an issue there.

**Comment by jrom99** [comment]
>fe probably doesn't match Fé because the e's although may be the same to us....they're completely different characters and thus Fuzzy search probably thinks they're not close.

Yes, I'm aware that most algorithms don't account for accented chars, so I was thinking of a match that uses "**F**éloch**e**". On Python, I used to use the [`unicodedata.normalize("NFKD", str)`](https://docs.python.org/3/library/unicodedata.html) to first normalize and decompress all strings (`é` -> `e + accent`, `half kana` -> `full width kana`) before comparison, but I'm not sure if C# has a similar library.

>flow and flm are closer to the result by length and so by matching ratio.

Thanks for the information, I thought the matcher would just use each character's order instead of taking typos into account. I disagree though that minimizing FN/FP is a waste of time, since FN are a source of confusion from a user's POV.

**Comment by nlogozzo** [comment]
Ok I improved the fuzzy algorithm where I:
* Increased acceptance ratio
* Normalized strings before comparing
* Ensure sorting of results from highest match to lowest match

Please try this build: https://github.com/NickvisionApps/Tagger/actions/runs/5743824488?pr=210 and let me know how it goes

**Comment by jrom99** [comment]
I installed it, but it seems to be more strict than before.

| String to match against "Féloche" | Before  | After |
| -------- | --------- | ------ |
| `fé`  | match  | match |
| `fe`  | not  | match |
| `fél` | match | match |
| `fel` | match | not |
| `fl` | not | not |
|  `flo` | match | not |
| `flow` | match | not |
| `flm` | match | not |

**Comment by nlogozzo** [comment]
> but it seems to be more strict than before.

Ok, I've lowered the strictness setting. Here's what will now match:
`fé`, `fe`, `fél`, `fel`, `flo`

I feel as this is the best inbetween as `flow`, `flm` doesn't make sense as matches.

**Comment by nlogozzo** [comment]
You can try with this build: https://github.com/NickvisionApps/Tagger/actions/runs/5744562179/job/15571090285

*It will show up on this page once the build finishes*

**Comment by nlogozzo** [comment]
Now remember, when we are searching we are looking for something to match what we searched....as @fsobolev said, fuzzy search is to just allow for the possibilities of spelling mistakes....so we don't want everything to match our search, we just wanted the closest things possible....pretty much an exact match give or take

**Comment by jrom99** [comment]
I can't find where to download the file on the link you provided, but it seems that the build has finished. Anyway, I notice now that it'd be better if this was a separate issue, since the crash itself has been solved.

**Comment by nlogozzo** [comment]
>I can't find where to download the file on the link you provided

Ah sorry, you just have to click the `Summary` tab and it will be there. Here's the right link anyway: https://github.com/NickvisionApps/Tagger/actions/runs/5744562179

> Anyway, I notice now that it'd be better if this was a separate issue, since the crash itself has been solved.

It's ok here....as I said anyway, I think the way it works in that provided build will be the final way.

**Comment by jrom99** [comment]
Just tried it, it's the best behavior overall! "Féloche" matches against both `fel`, `fél` and `flo`, but not against `flow` and `flm`. And every other match in my library makes sense as well.

**Comment by nlogozzo** [comment]
> Just tried it, it's the best behavior overall! "Féloche" matches against both `fel`, `fél` and `flo`, but not against `flow` and `flm`. And every other match in my library makes sense as well.

Great! Hope to have a stable release sometime this weekend if not, Monday the latest :)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.8.1
stable is here today!
