### ISSUE TITLE
Lots of error messages on the terminal

### ISSUE THREAD

**Issue by jrom99** [NickvisionApps/Tagger#219]
## Describe the bug

Hello, Tagger is outputting about 20 times the following messages when I click on the "tag actions" button on the hamburger menu for the first time, and about 4 times when I click them subsequently without closing the app.

```
(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 17:55:04.189: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 17:55:04.189: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
```

## System information

Tagger version: 2023.8.1 (from flathub)
OS: Ubuntu 23.04
Session type: wayland

## Additional context

[tagger_debug.txt](https://github.com/NickvisionApps/Tagger/files/12264665/tagger_debug.txt)

**Comment by nlogozzo** [comment]
Yeah I don't know why all these error Occurs. I feel like it occurs on all our apps with menu buttons....but no real usability issues result from it so 🤷‍♂️

@fsobolev any idea?

**Comment by fsobolev** [comment]
These errors appear not just with our apps, but with other apps too, even with GNOME Calculator, so I guess it's something with GTK 4.12.
Closing since it's not our bug and it doesn't really affect anything.

**Comment by jrom99** [comment]
I searched a bit and found this <https://gitlab.gnome.org/GNOME/gtk/-/issues/5892>, it seems that it'll be resolved soon!
