### ISSUE TITLE
[Enhancement] Different message when fetching metadata from MusicBrainz fails

### ISSUE THREAD

**Issue by jrom99** [NickvisionApps/Tagger#220]
Currently, when I try to fetch metadata using MusicBrainz for a given file the following message appears "Downloaded metadata for 0 files successfully" and no tag is changed.

I can find the songs on MusicBrainz but I'm not sure how to compare the AccoustId fingerprints (available as an image in the website, I think?) with the one provided in Tagger's interface. However, I'm almost sure they don't match, since my files usually have a different length from the ones provided AccoustId. I don't know if I can actually upload the music file here, but I tested with "George Ezra's Budapest" youtube version, which has a length of 3m37s versus the range 3m24-3m28 in [AccoustId](https://musicbrainz.org/recording/c63c4b83-2144-4c93-a6d4-39e85278d809/fingerprints).

Considering this, I think that the fetching itself fails since there is no match, but I can't be sure because the message is uninformative. In such cases I think a different message would be better.

## System information

Tagger version: 2023.8.1 (from flathub)
OS version: Ubuntu 23.04
Session type: wayland

**Comment by nlogozzo** [comment]
Here's a CI build you can try with the feature: https://github.com/NickvisionApps/Tagger/actions/runs/5771541449

**Comment by nlogozzo** [comment]
@jrom99  FYI see https://github.com/NickvisionApps/Tagger/issues/232

**Comment by nlogozzo** [comment]
Please try out the feature in this release: https://github.com/NickvisionApps/Tagger/releases/tag/2023.8.2-rc1
