### ISSUE TITLE
ID3 genres

### ISSUE THREAD

**Issue by icher** [NickvisionApps/Tagger#223]
Hi. How about convert `Genre` text entry to dropdown menu of ID3v1 genres?

https://en.wikipedia.org/wiki/List_of_ID3v1_genres

![841a20fe98a08c5debf1a3a863622b1092cba988](https://github.com/NickvisionApps/Tagger/assets/8604717/43e0667b-4670-4807-893c-0ab1b314f7cd)

**Comment by nlogozzo** [comment]
We went against using a `Gtk.ComboBox` with entry as it's deprecated. We build our own `AutocompleteBox` to use instead:
![image](https://github.com/NickvisionApps/Tagger/assets/17648453/5cf8b942-9a3a-4fdb-8b04-1a6db3d51915)

**Comment by nlogozzo** [comment]
Please try out the feature in this release: https://github.com/NickvisionApps/Tagger/releases/tag/2023.8.2-rc1
