### ISSUE TITLE
Cover art does not show in spotify

### ISSUE THREAD

**Issue by AlexNomadrg** [NickvisionApps/Tagger#230]
If I add a cover art or change some properties of a song with an existing cover art the artwork will disappear from Spotify.

latest flatpack release 
arch linux

**Comment by nlogozzo** [comment]
Spotify plays local music? I didn't know that...

I have to see what label Spotify expects from album art and I'll add it so it shows.

**Comment by nlogozzo** [comment]
Can I know what file type you are using? `mp3`, `wav`, flac`?

**Comment by AlexNomadrg** [comment]
I’m using mp3

> Can I know what file type you are using? `mp3`, `wav`, flac`?

**Comment by nlogozzo** [comment]
These are the requirements set by Spotify: https://support.spotify.com/us/artists/article/cover-art-requirements/

But it seems as this an issue many people are having:
https://www.reddit.com/r/spotify/comments/95gi6m/adding_album_artwork_to_local_files/
https://community.spotify.com/t5/iOS-iPhone-iPad/Adding-Cover-Art-to-Local-Files/td-p/33225

It seems that only adding cover art via iTunes is supported by Spotify 🤔

I'm going to send these requirements to our tag backend's (atldotnet) developer and see if there is anything we can do....

**Comment by fsobolev** [comment]
> ATL is not (and won't be) an image processing library, so all of these requirements should be checked before you embed the picture into the MP3.
>
> Maybe create a "Is my picture Spotify-ready?" feature that analyzes the submitted cover and fires a warning if these requirements aren't met?

I think creating a setting "Convert covers to Spotify-acceptable format" would work, and we will convert images before inserting them

**Comment by nlogozzo** [comment]
We found a fix for this and no setting is needed to be toggled. Just re-add album to already tagged files or add album art to new files and it will all show in Spotify!

Release will be out later tonight/tomorrow :)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.8.3
