### ISSUE TITLE
musicbrainz not working

### ISSUE THREAD

**Issue by legacychimera247** [NickvisionApps/Tagger#232]
everytime i try to lookup for musicbrainz info the app retrieves 0 informations, i guess it's not working then?

don't know if it's related but my acoustID key is correctly set...

**Comment by nlogozzo** [comment]
It's not that MusicBrainz "isn't" working, it's that AcoustID probably doesn't contain any information about your file.
We've improved the error messages that will be shown when no data is retrieved (see #220) for the next version.

But I think I found the bug on my no songs ever find a MBRID ...

**Comment by nlogozzo** [comment]
Turns out I had to explicitly ask AcoustId for musicbrainz ids...will be fixed in the next version :)

**Comment by nlogozzo** [comment]
Please try out the fix in this release: https://github.com/NickvisionApps/Tagger/releases/tag/2023.8.2-rc1
