### ISSUE TITLE
New Web Service - Download Lyrics For Music File

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/Tagger#240]
Now that there is Lyrics support in Tagger (#239), I'd be cool to have a web service to download the lyrics for a music file

*Needs planning: I have no idea what APIs are available to use for this*

**Comment by fsobolev** [comment]
Probably worth taking a look at [GiveMeLyrics](https://github.com/muriloventuroso/givemelyrics)

**Comment by jrom99** [comment]
Rhythmbox also has a [lyrics plugin](https://gitlab.gnome.org/GNOME/rhythmbox/-/tree/master/plugins/lyrics), but it's a bit outdated and contrived to work with (no specific APIs, it actually sends HTTP requests, parses the HTML pages and extract the lyrics).

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.9.0-beta1
