### ISSUE TITLE
Slow Tag saving on multiple files

### ISSUE THREAD

**Issue by DeWir3** [NickvisionApps/Tagger#248]
Saving Tags on multiple files at once takes a very long time. For example, with an audiobook with 12 files, 266 MB total size, removing the field "total tracks" on all 12 files at once took over 2.5 minutes to save. In Ear Tag by comparison, the same action finishes near-instantly. It shouldn't take nearly that long, so there might be something wrong with the way tags are saved.

**Comment by nlogozzo** [comment]
Tagger saves and works with a lot more information than EarTag so it's kind of expected. But 2.5 minutes is a lot...I will investigate and see what I can do to speed it up

**Comment by DeWir3** [comment]
I don't know how it works on the technical side, but can't it just "work with" the values that are changed? In puddletag the time needed to save seemed to depend on the amount of data saved to the tags, e.g. saving a large cover image to multiple files took longer (still not 2.5 minutes), while text-based changes saved very quickly.
Please disregard if too naive.

**Comment by Zeugma440** [comment]
@nlogozzo You might want to take a look at that section of the ATL FAQ : https://github.com/Zeugma440/atldotnet/wiki/4.-FAQ-(Frequently-Asked-Questions)#im-not-happy-with-atl-performance-is-there-a-way-to-improve-it-

**Comment by nlogozzo** [comment]
> @nlogozzo You might want to take a look at that section of the ATL FAQ : https://github.com/Zeugma440/atldotnet/wiki/4.-FAQ-(Frequently-Asked-Questions)#im-not-happy-with-atl-performance-is-there-a-way-to-improve-it-

I believe this slowdown is caused by us and not ATL. 
Currently `MusicFile` loads the `ATL.Track` and copies it's data to our own class and manipulates that and then on `Save` it loads the `ATL.Track` again, modifies it with our class' information, and saves it. So obviously we should just keep the `Track` instance and modify that and save it when needed instead of all this loading again and again.

**Comment by nlogozzo** [comment]
@Zeugma440 idk if you use linux / ever worked with it. But there is this packaging format known as `flatpak` which is mainly how the app is distributed.

Now upon testing running #262 locally (just pressing run in Rider) vs running [the flatpak build](https://github.com/NickvisionApps/Tagger/actions/runs/5893278978), I notice that the flatpak version is DRASTICALLY slower than running locally. The locally run version was able to save 18 files almost instantly...whereas the flatpak version took noticably 5-6 seconds to save those 18 files

Loading files doesn't seem to be affected, as both versions load 1168 files in the same amount of time (just a few seconds). 

So I don't know if this is an ATL issue or a flatpak issue. I will investigate a little more.
(FYI @fsobolev going to try enabling home access...)

**Comment by nlogozzo** [comment]
Ok so enabling `"--filesystem=home"` in the flatpak caused the saving speed to match that of the locally run version...so i've included that in #262.

**Comment by DeWir3** [comment]
I can confirm that I was using the flatpak version. I'll test when the update is out (possibly delayed due to absence).

**Comment by Zeugma440** [comment]
Flatpack being a sandboxed container, I guess file I/O layers are somehow virtualized unless you tell it so (hence `--filesystem=home`)

ATL uses low-level I/O intensively, with limited buffering. Seeing it slowing down on such environments is understandable.

I'm adding it to my FAQ. Thanks~

**Comment by nlogozzo** [comment]
@DeWir3 Quick question...are you music files stored in `~/Music`? (the music folder in your home directory)

**Comment by nlogozzo** [comment]
> Flatpack being a sandboxed container, I guess file I/O layers are somehow virtualized unless you tell it so (hence `--filesystem=home`)
> 
> ATL uses low-level I/O intensively, with limited buffering. Seeing it slowing down on such environments is understandable.
> 
> I'm adding it to my FAQ. Thanks~

Makes sense...is there a way we could improve this though? As for example with taglib# we didn't have this issue....

**Comment by Zeugma440** [comment]
> As for example with taglib# we didn't have this issue

I assume you're saying that after testing the very same scenario, using the very same files with both libraries. Not trolling here; we're talking about performance, and performance refactorings have to be backed by solid data.

That being said... at their core, Taglib# and ATL have different approaches to data manipulation. 

In my humble opinion, the Flatpack use case is not severe enough to justify a major refactoring of the library's inner workings, especially if you found a workaround.

**Comment by nlogozzo** [comment]
> I assume you're saying that after testing the very same scenario, using the very same files with both libraries. Not trolling here; we're talking about performance, and performance refactorings have to be backed by solid data.

Yes same set of files.

> That being said... at their core, Taglib# and ATL have different approaches to data manipulation.

Ah didn't know they differ that much. Either way ATL provides a lot more features and robustness compared to taglib. 

> In my humble opinion, the Flatpack use case is not severe enough to justify a major refactoring of the library's inner workings, especially if you found a workaround.

In the grand scheme of C# and gnome, yes I agree. Just a consideration as things grow

**Comment by nlogozzo** [comment]
Please try the beta and let me know how it goes: https://github.com/NickvisionApps/Tagger/releases/tag/2023.8.3-beta1 :)
