### ISSUE TITLE
[Feature] Add track numbers based on file-sorting/file name

### ISSUE THREAD

**Issue by DeWir3** [NickvisionApps/Tagger#249]
I often have albums that have the track numbers in their file names, but not in their tags. An option to add track numbers based on alphabetical (or other) file-sorting or from a certain part of the file name would be very helpful. In puddletag for example you can do that with the autonumbering wizard.

**Comment by nlogozzo** [comment]
If you have track numbers at the beginning of the file name it will sort based on that automatically...but in random places no.

I'd recommend adding the track nunbers to the tags and then going into preferences and sorting by album or track. Sorting by album will sort by album and then track numbers whereas sorting by track eill sort by track number then album.

**Comment by nlogozzo** [comment]
What I do recommend is using the convert filename to Tag feature and providing a custom format string to bulk extra the track numbers from the filenames and put it in the tags automatically.

**Comment by DeWir3** [comment]
> If you have track numbers at the beginning of the file name it will sort based on that automatically...but in random places no.
> 
> I'd recommend adding the track nunbers to the tags and then going into preferences and sorting by album or track. Sorting by album will sort by album and then track numbers whereas sorting by track eill sort by track number then album.

I think I didn't express myself clearly. Sorting is not my issue. I don't want to add track numbers to the tags of a bunch of files manually one by one. If the files are already in the right order, I would like to be able to just add the track numbers automatically based on that order starting from 1.

> What I do recommend is using the convert filename to Tag feature and providing a custom format string to bulk extra the track numbers from the filenames and put it in the tags automatically.

It might be a documentation issue (I haven't found any), but it is not clear to me, how to just grab the track number from the file name and add that to the tag, while ignoring the rest of the filename and not touching any other tag fields.

**Comment by nlogozzo** [comment]
> It might be a documentation issue (I haven't found any), but it is not clear to me, how to just grab the track number from the file name and add that to the tag, while ignoring the rest of the filename and not touching any other tag fields.

Ah yeah we don't really have a way to ignore fields...but I can implement that feature...something like `%%` to ignore all values. So a format string of `%%- %track%. %%` would just extract the track number between the `-` and `.`

**Comment by DeWir3** [comment]
> Ah yeah we don't really have a way to ignore fields...but I can implement that feature...something like `%%` to ignore all values. So a format string of `%%- %track%. %%` would just extract the track number between the `-` and `.`

That would work for me!

**Comment by nlogozzo** [comment]
Use #251 to track
