### ISSUE TITLE
Add ability to ignore in format string

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/Tagger#251]
`%%` would represent ignoring a part of the string.

For example if the filename is: `01. Artist1- Song1`
The format string could be: `%tract%. %%` to just extra `01` and ignore everything else

**Comment by nlogozzo** [comment]
Please try the beta and let me know how it goes: https://github.com/NickvisionApps/Tagger/releases/tag/2023.8.3-beta1 :)

**Comment by nlogozzo** [comment]
@DeWir3 ^

**Comment by DeWir3** [comment]
I tried this in 2023.8.3 now and it worked great. Thank you for this as well!
I would recommend adding a small info bubble with the available values as well :)
