### ISSUE TITLE
Support webp format for covers

### ISSUE THREAD

**Issue by TitouanReal** [NickvisionApps/Tagger#253]
I tried to use an image in webp format as a cover. Once I choose the image from the File portal and Tagger is supposed to handle it, it crashes. I tried different webp images on different songs with the same result.
 When running the app from the terminal, this error message appears:

bash-5.2$ flatpak run org.nickvision.tagger
Unhandled exception. GLib.GException: Format d’image non reconnu
   at GLib.Error.ThrowOnError(ErrorHandle error)
   at Gdk.Texture.NewFromBytes(Bytes bytes)
   at NickvisionTagger.GNOME.Views.MainWindow.SelectedMusicFilesPropertiesChanged() in /run/build/org.nickvision.tagger/NickvisionTagger.GNOME/Views/MainWindow.cs:line 1128
   at GLib.Internal.SourceFuncNotifiedHandler.<.ctor>b__4_0(IntPtr userData)

Suggesting this is indeed the format of the image that causes the problem.

I use Fedora 38.

**Comment by nlogozzo** [comment]
Please try the beta and let me know how it goes: https://github.com/NickvisionApps/Tagger/releases/tag/2023.8.3-beta1 :)

**Comment by TitouanReal** [comment]
I tried it and it seems to just work now.
Thank you very much for the fix!

**Comment by nlogozzo** [comment]
> I tried it and it seems to just work now.
> Thank you very much for the fix!

Stable release should be out by Friday :)

**Comment by nlogozzo** [comment]
I noticed that I never updated the flatpak manifest file on flathub to include the webp loader so this feature never worked on V2023.8.3 stable through flathub....this has been fixed and it should all work now with today's V2023.9.0 release :)
