### ISSUE TITLE
have the ability to keep current cover art

### ISSUE THREAD

**Issue by legacychimera247** [NickvisionApps/Tagger#258]
althought i said musicbrainz integration does not work :P  there are some exceptions where it works, and this is nice, very nice, but most of the times cover arts from musicbrainz are way worst than the one i already have, so it would be nice to have an ability to save all the data but keep the original cover art...

**Comment by nlogozzo** [comment]
There is the option already in Preferences. 

It's called `Overwrite Album Art with MusicBrainz` and you can turn it off to keep the original art.
