### ISSUE TITLE
UI inconsistencies

### ISSUE THREAD

**Issue by legacychimera247** [NickvisionApps/Tagger#260]
hello, having a look at this, are you sure it's the right image?seems like an image with a border has been glued to the one under

![image](https://github.com/NickvisionApps/Tagger/assets/22254556/f8d492fc-156d-47eb-8da1-5759fe4234ff)

don't you think is a little out of place?

**Comment by nlogozzo** [comment]
This is `music-library-symbolic`...I think it fits.

Do you have another icon in mind that we could use?

**Comment by legacychimera247** [comment]
honestly no idea, but anyway if it's a gnome thing then it's not a bug

i just think it looks a bit out of place in this beautiful crafted application...

**Comment by nlogozzo** [comment]
Yeah like I said that's just the icon itself:
![image](https://github.com/NickvisionApps/Tagger/assets/17648453/3cf57d69-924a-4951-894d-19a07988ba92)
