### ISSUE TITLE
Select multiple files without keyboard

### ISSUE THREAD

**Issue by 239** [NickvisionApps/Tagger#283]
Unless I missed something, there is no way to select multiple files without a keyboard. It could be really handy to have a **Select all** button or other selection options in the context menu.
An indication of how many files are selected next to the total length/size would also be useful: 8/12 - 00:36:21 - 70,82 MiB

**Comment by nlogozzo** [comment]
I can add a select all button next to the search box...and will also implemented that number of selected items indicator

**Comment by nlogozzo** [comment]
![image](https://github.com/NickvisionApps/Tagger/assets/17648453/11feb584-e7d1-48b0-8fe8-eb598fdb77d3)

**Comment by nlogozzo** [comment]
Here's a better screenshot with selected count in the bottom bar: 
![image](https://github.com/NickvisionApps/Tagger/assets/17648453/2605530e-1e94-41a2-bcdd-ab4ac3c1ca67)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.9.0-beta1
