### ISSUE TITLE
Embedded covers fail to load in opus files

### ISSUE THREAD

**Issue by 239** [NickvisionApps/Tagger#286]
Images embedded with **Ex Falso** are displayed for _flac_ files. But for _opus_ (ogg) files they are missing and appear only as a `metadata_block_picture` custom property.
I'm not sure on which side the problem is, since **mpv** shows the covers embedded with **Ex Falso** and **Tagger** correctly.

**Comment by nlogozzo** [comment]
Could you send me the ogg file tagged with Ex Falso that shows up weird in Tagger? Either send it in a zip here or if it's too big, email me @ nlogozzo225@gmail.com

**Comment by 239** [comment]
[Entropyyy.zip](https://github.com/NickvisionApps/Tagger/files/12454568/Entropyyy.zip)

**Comment by nlogozzo** [comment]
https://github.com/Zeugma440/atldotnet/issues/225

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.9.0-beta1
