### ISSUE TITLE
Handle special characters in filenames

### ISSUE THREAD

**Issue by AbrarSL** [NickvisionApps/Tagger#288]
When using the tag to filename option the application crashes if the tag contains a problematic character like '\\' in it. Perhaps a substitute character could be placed instead?

**Comment by nlogozzo** [comment]
I know other characters may break but `"` works for me:
![image](https://github.com/NickvisionApps/Tagger/assets/17648453/205c64f5-443f-42af-a202-c40ff58b219e)

Could you run Tagger in the terminal (`flatpak run org.nickvision.tagger`) and share the error messages when the app crashes?

**Comment by AbrarSL** [comment]
I meant to write '\\' but I forgot to escape the slash. The slash is what was causing the app to crash.

**Comment by nlogozzo** [comment]
> I meant to write '\\' but I forgot to escape the slash. The slash is what was causing the app to crash.

Ah ok that makes sense...I'll have it replace all invalid with a `_`.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.9.0-beta1
