### ISSUE TITLE
In versions of the application starting from 2023.8, it is not possible to apply changes only to files whose tag does not match the specified one

### ISSUE THREAD

**Issue by SokolovskyMaxim** [NickvisionApps/Tagger#289]
In versions of the application starting from 2023.8, it is not possible to apply changes only to files whose tag does not match the specified one

1. All files are highlighted.
2. All files in the directory are overwritten, not just those with a tag that does not match

For example, a folder stores music that has one album tag. Several other songs that don't have this tag are added to it. In order not to manually change each song, you can select all of them and apply the changes only to those files that do not have a specified tag. Before version 2023.7, this could be done. Not now

This is how it looked before version 2023.7
![Снимок экрана от 2023-08-30 18-58-26](https://github.com/NickvisionApps/Tagger/assets/106545001/5456231b-86d1-4bb5-bbbc-71128bc24f41)

**Comment by nlogozzo** [comment]
Ah I see what you are saying...ok let me look into it

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.9.0-rc1
