### ISSUE TITLE
[Feature Request] Add an option to create a m3u playlist file for open files

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [NickvisionApps/Tagger#311]
I'm currently using Kid3 as my music tagger of choice but I want to use Tagger as I like its UI much more. But there is one feature missing that prevents me from using it as my default tagger and that is the creation of a playlists.
I find this to be very handy while modifying the tags and names of my audio files to reflect the changes in my playlists to keep them functional.
There is also no program currently in the current gnome core apps or gnome circle ecosystem to provide playlist creation and handling.
I think this would be a great fit for this application.

**Comment by nlogozzo** [comment]
@Sebastian-Hirsch Are there any other options besides these that you'd need?
![image](https://github.com/NickvisionApps/Tagger/assets/17648453/022e441d-9bf3-4d55-a6e1-9a3fe523913c)

Here is the list of supported formats as well: `"M3U", "PLS", "FPL", "XSPF", "SMIL", "ASX", "B4S", "DPL"`

**Comment by nlogozzo** [comment]
> Where does the playlist get saved?

In the folder it was created for.

> Is there an option to change the save path?

No the user would have to move it manually.

**Comment by nlogozzo** [comment]
Ok so we added full playlist support...meaning you can now open a playlist file in Tagger itself and add/remove files to the playlist all from within the app!

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.9.1-rc1
