### ISSUE TITLE
[Feature Request] Set sorting order by default to file path and add separator to file list when folder with subfolders got opened

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [NickvisionApps/Tagger#312]
When I open a folder in Tagger that contains multiple subfolders with music files, the file list is ordered alphabetically which makes using Tagger very confusing as now my albums will get mixed up.

I know that there is an option in the settings to change the ordering, but this is not the default so it can confuse new users with bigger more structures music collections. Setting the sorting order option to file path by default would help here.
What would also help would be a separator in the file list to make a more clear distinction between different folders/albums. This would make reading the file list easier and more comfortable.

![Bildschirmfoto vom 2023-09-08 22-18-08](https://github.com/NickvisionApps/Tagger/assets/41188546/5f27e660-9070-4fdf-b3ad-4adda96a5a7f)
![Bildschirmfoto vom 2023-09-08 22-18-35](https://github.com/NickvisionApps/Tagger/assets/41188546/b8a93681-0308-4310-916b-c7191711f4ec)

One could just open the subfolders one after another, but that would make using Tagger for big music collections very tedious.

And sorry for the long title, I could not come up with a more concise one.

**Comment by fsobolev** [comment]
> I know that there is an option in the settings to change the ordering, but this is not the default so it can confuse new users with bigger more structures music collections. Setting the sorting order option to file path by default would help here.

Sorting by path actually places 10 after 1 but before 2 if your files don't have trailing 0 in their names. But I agree that another option would be a better default, IMO sorting by artist is the best.

**Comment by Sebastian-Hirsch** [comment]
Ah, that trailing zero issue is quite annoying. Sorting by artist on the other hand would require correctly filled out tags, which is sadly not the norm, so this could also result into sketchy sorting results. In the end, I open Tagger to improve the tags to make sorting by artist a possibility.

How does the artist option work if I open a folder with albums that are all from the same artist?

**Comment by fsobolev** [comment]
> How does the artist option work if I open a folder with albums that are all from the same artist?

Albums from the same artist are sorted alphabetically by name, then tracks from an album are sorted by number (correctly: 1, 2 .. 10; not 1, 10, 2).

**Comment by fsobolev** [comment]
After thinking more, sorting by artist is good when tags are at least partially filled, but for completely untagged files it's a mess. Sorting by path will indeed be the best option when the order of numbered files will be fixed.

Headers are implemented now in #314 and show different things depending on sorting (or don't show at all for sorting by title for example).

![image](https://github.com/NickvisionApps/Tagger/assets/117388856/1ec1eeb5-51c9-43cd-a0c7-22bc001e637c)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.9.1-rc1
