### ISSUE TITLE
Make Tagger remember window size (and position)

### ISSUE THREAD

**Issue by edisso999** [NickvisionApps/Tagger#327]
If you make your Tagger window bigger (which I always do, since the default size is somewhat small) you have to redo this after starting Tagger the next time. Tagger should remember (save) its window size and position.

**Comment by fsobolev** [comment]
It's technically impossible with GTK to get and set window position.
But window size - sure.

**Comment by nlogozzo** [comment]
Position of a window we are unable to change due to gtk 4 not allowing it.

But the size we definitely can.

**Comment by nlogozzo** [comment]
> It's technically impossible with GTK to get and set window position.
> But window size - sure.

Beat me too it :)

**Comment by fsobolev** [comment]
> Position of a window we are unable to change due to gtk 4 not allowing it.
> 
> But the size we definitely can.

Damn we sent comments literally at the same second 😂

**Comment by edisso999** [comment]
Now that's what I call a fast reponse! Thanks!
