### ISSUE TITLE
Unable to open for a tune.

### ISSUE THREAD

**Issue by ben2talk** [NickvisionApps/Tagger#337]
When selecting a file that wants tagging, it's not possible to open with tagger - Tagger simply opens with an 'Open Folder' dialogue which is cumbersome as the paths to music files aren't always simple to navigate via clicking.

Neither is it possible to drag a playlist entry on to tagger.

Neither is it possible to drag a file onto Tagger.

For my example, I tried copying the location of the file - it seems you can only load an entire folder. After that, it appears that there are 'File Properties' at the bottom of the list, which gives no file properties - instead showing 'Fingerprint - Calculating' with a forever rotating cog.

I found a solution to this issue (sorry) - is simply to use Picard.

**Comment by nlogozzo** [comment]
> When selecting a file that wants tagging, it's not possible to open with tagger - Tagger simply opens with an 'Open Folder' dialogue which is cumbersome as the paths to music files aren't always simple to navigate via clicking.

First off, Tagger is meant as a music library taggger hence why we support opening folders or playlists to get a collection of music files.

As far as being hard to find a folder with the `Open Folder ` dialog...if you have the folder open in nautilus already you can simply right click inside that folder, click `Open With...` then select Tagger and it will automatically open in Tagger.

> Neither is it possible to drag a playlist entry on to tagger.

What do you mean by playlist entry? Do you mean a playlist file like a `.m3u` file? If so, did you try the latest `V2023.9.1` and try with the latest `Open Playlist` feature? What's the format of the playlist file?

> that there are 'File Properties' at the bottom of the list, which gives no file properties

`Fingerprint` is a property of the file? What other file properties are you expecting (besides duration and file size which are shown at the top of the list underneath the album art)?

> Calculating' with a forever rotating cog.

This sounds like an ffmpeg/fpcalc bug...what the file format of the music file? would you be able to attach it here so I can test?

> I found a solution to this issue (sorry) - is simply to use Picard.

Welcome to Open Source, free to chose whatever software you please! However, Tagger is pretty new and worked on by just two developers, me and @fsobolev so you have to be patient with us. As you can tellby our issues list we fix every issue in a pretty fast manner so just have to work with us to fix and make the app better :)
