### ISSUE TITLE
Date Tag Property

### ISSUE THREAD

**Issue by kissthermite** [NickvisionApps/Tagger#363]

**Comment by nlogozzo** [comment]
Year is stored as a single integer value in tags and thus cannot be a full date as per ID3 tag specification.

We can however expose `RecordingDate` or `PublishingDate` as an additional property which can be a full date. 

Please let me know which of the two properties you'd prefer.

**Comment by nlogozzo** [comment]
Please test the latest beta release with this feature: https://github.com/NickvisionApps/Tagger/releases/tag/2023.10.0-beta2 and let us know how it goes!

*Will be available via `flathub-beta` within the hour*

**Comment by kissthermite** [comment]
> Please test the latest beta release with this feature: https://github.com/NickvisionApps/Tagger/releases/tag/2023.10.0-beta2 and let us know how it goes!
> 
> _Will be available via `flathub-beta` within the hour_

![image](https://media.discordapp.net/attachments/1139923418767175764/1165123813697126511/Screenshot_from_2023-10-21_10-04-43.png?ex=6545b51c&is=6533401c&hm=e4aa11a44e2db04de369c7dbbab1953884ce67d4de7396533accd28f124dd3b5&=)

`Publishing Date` tag also work as intended, and those `Pick a date` function is  just "chef’s kiss ". Nickvision  is real.

**Comment by kissthermite** [comment]
@nlogozzo

**Comment by nlogozzo** [comment]
I'm unable to reproduce the issue: https://i.imgur.com/lkYdTRj.mp4

My library is all `mp3` files though. I will try with a `flac` file however like you have.

**Comment by nlogozzo** [comment]
Looks like it's an issue with `flac` files...will get it fixed :)

**Comment by nlogozzo** [comment]
https://github.com/Zeugma440/atldotnet/issues/235

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.10.0-rc1
