### ISSUE TITLE
Disc Tag Property

### ISSUE THREAD

**Issue by kissthermite** [NickvisionApps/Tagger#365]
Add `Disc` & `Disc Total` as an additional properties.

**Comment by nlogozzo** [comment]
Will add these to `Addition Properties` 

Note to self, add an option to show and hide additional properties section for those who want/don't want it. Also, remember this option in config, default shown

**Comment by nlogozzo** [comment]
GNOME:
![image](https://github.com/NickvisionApps/Tagger/assets/17648453/3dee2d41-eb53-43b1-858e-4759c10f9bc7)

Windows:
![image](https://github.com/NickvisionApps/Tagger/assets/17648453/73576a30-af5f-452e-adde-9ecba8fc79d5)

**Comment by nlogozzo** [comment]
Please test the latest beta release with this feature: https://github.com/NickvisionApps/Tagger/releases/tag/2023.10.0-beta2 and let us know how it goes!

*Will be available via `flathub-beta` within the hour*

**Comment by kissthermite** [comment]
> Please test the latest beta release with this feature: https://github.com/NickvisionApps/Tagger/releases/tag/2023.10.0-beta2 and let us know how it goes!
> 
> _Will be available via `flathub-beta` within the hour_

Will do!

**Comment by nlogozzo** [comment]
> Will do!

The build was just uploaded and published. 
Give it literally 5-10 minutes and the update will be downloadable from the `flathub-beta` repo 😅
*Instructions on the release page of how to get from flathub-beta if you never have before*

**Comment by kissthermite** [comment]
> Please test the latest beta release with this feature: https://github.com/NickvisionApps/Tagger/releases/tag/2023.10.0-beta2 and let us know how it goes!

![image](https://media.discordapp.net/attachments/1139923418767175764/1165138675290603600/Screenshot_from_2023-10-21_11-04-43.png?ex=6545c2f3&is=65334df3&hm=b0215a37160b9cb0739fc86a01579503cf2af17bba9245d743ff6f7495f5fe99&=&width=575&height=626)

`Disc Number` & `Disc Total` tag itself working as intended. However `Sort Files By` `Album` could do a little rework to accommodate `Disc` tag. The current behavior only take a consideration of `Track`. Also a little nitpick, why `Track` & `Disc Number` and not  `Track Number` & `Disc Number` or `Track` & `Disc`?

**Comment by kissthermite** [comment]
> However `Sort Files By` `Album` could do a little rework to accommodate `Disc` tag.

What i mean by this is it should be `Disc Number` first then `Track Number`
so that when you have an Album that have multiple Disc E.g. Disc 1 contain 15 Track and the format of the `Track Number` is 1-15 and and Disc 2 contain 10 Track whether the `Track Number` is 1-10 or 16 -25 the sort will be the same.

**Comment by nlogozzo** [comment]
> Also a little nitpick, why Track & Disc Number and not Track Number & Disc Number or Track & Disc?

As per tag specifications, track number is referred to as `Track` and disc number referred to as `Disc Number`. See https://community.mp3tag.de/t/a-few-questions-about-the-disc-number-disc-total-columns/18698/3 :
> Value: %DISCNUMBER%
Field: %DISCNUMBER%
Value: %TRACK%
Field: %TRACK%

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.10.0-rc1
