### ISSUE TITLE
Additional information of `Album Art` such as Image Type, Width & Height or Resolution.

### ISSUE THREAD

**Issue by kissthermite** [NickvisionApps/Tagger#366]
Image mock-up.
Picture 1: resolution as an overlay, like `Front` & `Back` on a corner of `Album Art`
Picture 2: a pop-up window showing the aforementioned additional information.

![1](https://cdn.discordapp.com/attachments/1139923418767175764/1164208881568845865/1.jpg?ex=65426103&is=652fec03&hm=6f446642de1675d30d8199efcee67c6db2dd96c4d43bd4a71bb8d2175be654ee&)

![2](https://cdn.discordapp.com/attachments/1139923418767175764/1164208881996669038/2.png?ex=65426103&is=652fec03&hm=a418aa1daf42021f0f7f0ac3d178441f6b5ae382bb554e956ea164ec0c1793c9&)

**Comment by nlogozzo** [comment]
Wow this looks really cool!

Maybe what we could do is where you put the resolution in Picture 1 instead we can put an info icon that the user can click to bring up the image properties dialog shown in Picture 2.

**Comment by nlogozzo** [comment]
Here's WinUI:
![image](https://github.com/NickvisionApps/Tagger/assets/17648453/93377368-037d-46d2-92f3-ea9bf1b7962c)

*GNOME coming next...*

**Comment by nlogozzo** [comment]
And here's GNOME:
![image](https://github.com/NickvisionApps/Tagger/assets/17648453/c8153578-db4d-4e40-a3bc-429a292839cb)

*Note we will change the row style to have the [property style class](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/style-classes.html#property-rows) once we support libadwaita 1.4*

**Comment by nlogozzo** [comment]
Please test the latest beta release with this feature: https://github.com/NickvisionApps/Tagger/releases/tag/2023.10.0-beta2 and let us know how it goes!

*Will be available via `flathub-beta` within the hour*

**Comment by kissthermite** [comment]
> Please test the latest beta release with this feature: https://github.com/NickvisionApps/Tagger/releases/tag/2023.10.0-beta2 and let us know how it goes!
> 
> _Will be available via `flathub-beta` within the hour_

![image](https://media.discordapp.net/attachments/1139923418767175764/1165122200794304553/Screenshot_from_2023-10-21_09-59-29.png?ex=6545b39b&is=65333e9b&hm=f54002b8f8c04872137f476b81cdda3b7a3c3d76474d391e6ec7e42279925126&=&width=308&height=596)

![image](https://media.discordapp.net/attachments/1139923418767175764/1165121763580055574/Screenshot_from_2023-10-21_09-57-35.png?ex=6545b333&is=65333e33&hm=b08aeeaeb6a31bf4cbf8cdff6ef6c390ac078ae9feb1db6737b17e5810613156&=)

Working as intended, and it does look good. I love it!
