### ISSUE TITLE
Add `Limit Filename Characters` Option

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/Tagger#372]

**Comment by nlogozzo** [comment]
![image](https://github.com/NickvisionApps/Tagger/assets/17648453/c600348b-ed13-4878-a873-03fc98f53ef9)

*Ignore the non-rounded corners and poor fonts...running from WSL*

**Comment by nlogozzo** [comment]
Please test the latest beta release with this feature: https://github.com/NickvisionApps/Tagger/releases/tag/2023.10.0-beta2 and let us know how it goes!

*Will be available via `flathub-beta` within the hour*

**Comment by kissthermite** [comment]
> Please test the latest beta release with this feature: https://github.com/NickvisionApps/Tagger/releases/tag/2023.10.0-beta2 and let us know how it goes!
> 
> _Will be available via `flathub-beta` within the hour_

> Please test the latest beta release with this fix: https://github.com/NickvisionApps/Tagger/releases/tag/2023.10.0-beta2 and let us know how it goes!

`Limit Filename Characters` does working wonderfully!

![name](https://media.discordapp.net/attachments/1139923418767175764/1165148989516165121/Screenshot_from_2023-10-21_11-45-51.png?ex=6545cc8e&is=6533578e&hm=7913f0d9aa74dd46ca45298a68d6f7dc164f2d92af2256c27a8a5d0fbad43d9e&=&width=692&height=596)

---

Before `Tag to File Name` conversion
![name](https://media.discordapp.net/attachments/1139923418767175764/1165148880812396544/Screenshot_from_2023-10-21_11-44-55.png?ex=6545cc74&is=65335774&hm=41d7095ba2e1187f1ef54e6b049acad02a650a0dbd050f13ced14a7b143a616c&=&width=548&height=596)

---

After `Tag to File Name` conversion with `Limit Filename Characters` turned on and Tag contain forbidden printable ASCII characters of Windows
![name](https://media.discordapp.net/attachments/1139923418767175764/1165148881210843136/Screenshot_from_2023-10-21_11-45-13.png?ex=6545cc74&is=65335774&hm=873eac0e0bc1d7e82cbbb0214d207d67d6b1ff7e72ebe36b632122d30a829291&=&width=548&height=596)
