### ISSUE TITLE
Remember Format String

### ISSUE THREAD

**Issue by kissthermite** [NickvisionApps/Tagger#375]
---

`%artist%- %title%`
 ![%artist%- %title%](https://media.discordapp.net/attachments/1139923418767175764/1164961610750771220/Screenshot_from_2023-10-20_23-20-11.png?ex=65451e0b&is=6532a90b&hm=7a8452240746a951afbfb00f0f93a1b91af7dcd8e3a21df15f5071c981069bd2&=)

`Artist1- Song1`
![Artist1- Song1.mp3](https://media.discordapp.net/attachments/1139923418767175764/1164868658351329310/IMG_20231020_171032.jpg?ex=6544c77a&is=6532527a&hm=b0a1c84ac96cad2bca8001fb4d6c07607c6d62e73bb059beb08bbfee62069c14&=)

---

`%artist% - %title%`
 ![%artist%- %title%](https://media.discordapp.net/attachments/1139923418767175764/1164961610994045010/Screenshot_from_2023-10-20_23-20-56.png?ex=65451e0c&is=6532a90c&hm=5978bf1a577cbe58fd2664cfedd933c78d8fe190e9f7c08716df9c7b2a9fa1f6&=)

`Artist1 - Song1`
![Artist1 - Song1.mp3](https://media.discordapp.net/attachments/1139923418767175764/1164868658623950878/IMG_20231020_171121.jpg?ex=6544c77a&is=6532527a&hm=516577aaf87369a894b249ec89ee30adef846a6faebe0b9d4c30046642a1605e&=)

---

![Tagger Help, Format Strings](https://media.discordapp.net/attachments/1139923418767175764/1164864178708824114/5.png?ex=6544c34e&is=65324e4e&hm=7839c16340bace9da1b5314c1bb5bfc833e5d2e4f4ee88e93cbc8372cb2958fc&=&width=720&height=307)

---

I guess it's a typo? But then again it's quite widespread if it's indeed a typo, because not only `%artist%- %title%` but also the other suggestions such as `%title%- %artist%` & `%track%- ℅title℅`. I'm on Fedora Silverblue, latest version of Tagger (flatpak) btw.

**Comment by nlogozzo** [comment]
So the `File Name to Tag` feature is what takes a file name and converts it to a tag. For example, `Artist1 - Song1.mp3` can be turned into the tag where`Artist=Artist1` and `Title=Song1`.  This feature has no effect on changing the actual file name (that's `Tag to File Name`)

The format string provided to `File Name to Tag` is to tell the function how to parse your filename and read tag data from it.

So if you have the filename `Artist1- Song1.mp3` or `Artist1 - Song1.mp3` (with or without the space), the format string `%artist%- %title%` will read the artist as `Artist1` and title as `Song1` for both versions of the file name.

If we changed the default format string to `%artist% - %title%` with the space, the file name `Artist1- Song1.mp3` will fail as it will look for a space before the `-` and it obviously doesn't have one.

Hence why the documentation is written the way it is to show that no matter if you have the space before the `-` or not, the format string without the space will work correctly.

**Comment by kissthermite** [comment]
> So the `File Name to Tag` feature is what takes a file name and converts it to a tag. For example, `Artist1 - Song1.mp3` can be turned into the tag where`Artist=Artist1` and `Title=Song1`. This feature has no effect on changing the actual file name (that's `Tag to File Name`)
> 
> The format string provided to `File Name to Tag` is to tell the function how to parse your filename and read tag data from it.
> 
> So if you have the filename `Artist1- Song1.mp3` or `Artist1 - Song1.mp3` (with or without the space), the format string `%artist%- %title%` will read the artist as `Artist1` and title as `Song1` for both versions of the file name.
> 
> If we changed the default format string to `%artist% - %title%` with the space, the file name `Artist1- Song1.mp3` will fail as it will look for a space before the `-` and it obviously doesn't have one.
> 
> Hence why the documentation is written the way it is to show that no matter if you have the space before the `-` or not, the format string without the space will work correctly.

Just realized i sent the wrong Screenshot on both example, it's supposed to be Tag to File Name

**Comment by kissthermite** [comment]
Now that i actually look real close at my screenshot the `Tagger Help`, `Format String` section does indeed refer to `File name to Tag`. Kek I'm such an idiot. However Isn't `Tag to File name` suggestions have a space before dash? So that it output `Artist - Song` AKA the standard music file naming?

**Comment by kissthermite** [comment]
Format string suggestions for `File Name to Tag` does make a lot of sense.
![2](https://media.discordapp.net/attachments/1139923418767175764/1164968584204783657/Screenshot_from_2023-10-20_23-48-33.png?ex=6545248a&is=6532af8a&hm=31313746302a3ff096e9ffc58dace87896b8b1fd0f87fec09135054179a3c159&=)


---

But is there also a reason as for why `Tag to File Name` format string suggestions doesn't have space before dash?
![1](https://media.discordapp.net/attachments/1139923418767175764/1164968583877632052/Screenshot_from_2023-10-20_23-48-20.png?ex=6545248a&is=6532af8a&hm=10bfc3df0b0b59918555dbc34a6437ff90ada41ddf9984338dc060969698eb0e&=)

I guess there's some that preferred it that way. If that's the case i would love to be able to save custom `Format String` so that i doesn't have to type in every time i'm doing `Tag to File Name` conversion with my preferred why of file name structure.

**Comment by nlogozzo** [comment]
> But is there also a reason as for why Tag to File Name format string suggestions doesn't have space before dash?

Consistency with `File Name to Tag`. We just have to make one array of strings instead of two 😂

> I guess there's some that preferred it that way. If that's the case i would love to be able to save custom Format String so that i doesn't have to type in every time i'm doing Tag to File Name conversion with my preferred way of file name structure.

You know what, I will make it where the previous format string (whether it be one from the list or custom) will be remembered and automatically selected/filled-in the next time you open the dialog.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.10.0-rc1

**Comment by nlogozzo** [comment]
> https://github.com/NickvisionApps/Tagger/releases/tag/2023.10.0-rc1

Flathub was having some slowness issues before but finally got the update uploaded and published. Should be available via `flathub-beta` within a few minutes :)
