### ISSUE TITLE
Wrong total time displayed when multiple files are selected

### ISSUE THREAD

**Issue by TitouanReal** [NickvisionApps/Tagger#379]
When multiple songs are selected, the total time is displayed under the album cover, with format hh:mm:ss.

On version 2023.9.1, Flathub package, the hh part is always 00 for me. I was editing metadata of some albums with a lot of songs and total times of more than one or tow hours, and even though the mm:ss part is correctly displayed, the hh still has a value of 00.

Example:
- real total time: 01:00:53
- displayed time: 00:00:53

I used French locale if that changes anything.

I don't know if this bug was already present on earlier versions of the app.

Thanks for this great app by the way :)

**Comment by nlogozzo** [comment]
This was fixed in main a little bit ago.

Please try the latest beta release: https://github.com/NickvisionApps/Tagger/releases/tag/2023.10.0-beta2
