### ISSUE TITLE
`VORBIS-VENDOR` on flac & opus, `info.ISFT` on wav Custom Properties are unremovable, The same behavior aren't present on mp3 and m4a

### ISSUE THREAD

**Issue by kissthermite** [NickvisionApps/Tagger#385]
![1](https://media.discordapp.net/attachments/1139923418767175764/1165857733107527760/Screenshot_from_2023-10-23_10-37-32.png?ex=654860a0&is=6535eba0&hm=be173e0cc6a54492d3a72a60d0d41294c3bff8da1a30bf3a76a36186bfb45412&=&width=575&height=626)

![2](https://media.discordapp.net/attachments/1139923418767175764/1165857733438873720/Screenshot_from_2023-10-23_10-37-37.png?ex=654860a0&is=6535eba0&hm=dfc3658d8d374a9f644ee08b29be63af4dd5100658470f3c1450076cbb9f9005&=&width=575&height=626)

![3](https://media.discordapp.net/attachments/1139923418767175764/1165857733774409749/Screenshot_from_2023-10-23_10-37-39.png?ex=654860a0&is=6535eba0&hm=41cf1e9fb9e42a90b439ca3d5496a8af43ac2f5a0d40073ee968159639599667&=&width=575&height=626)

---

![1](https://media.discordapp.net/attachments/1139923418767175764/1165857734319681658/Screenshot_from_2023-10-23_10-37-50.png?ex=654860a0&is=6535eba0&hm=3c087917b256f709b9eda3625494f44b07c69d2b846093300e28a60659f27322&=&width=575&height=626)

![2](https://media.discordapp.net/attachments/1139923418767175764/1165857734755885066/Screenshot_from_2023-10-23_10-37-52.png?ex=654860a0&is=6535eba0&hm=54bc1992d279c7580d3e6f2427c9011f9aece85c0b48373793e3001c19f0c625&=&width=575&height=626)

![3](https://media.discordapp.net/attachments/1139923418767175764/1165857735095615498/Screenshot_from_2023-10-23_10-37-54.png?ex=654860a0&is=6535eba0&hm=fd61e4b659ef4488695a50b9908fe1af973aac3b8f1ba57fe71243ca3a899264&=&width=575&height=626)

**Comment by nlogozzo** [comment]
I believe these fields are required parts of the file's tag header and shouldn't really be considered "custom properties". I will find out...

**Comment by nlogozzo** [comment]
https://github.com/Zeugma440/atldotnet/issues/236

**Comment by kissthermite** [comment]
Wait. The proposed solution is to remove `VORBIS VENDOR`? how about moving it to `File Properties` instead?

**Comment by nlogozzo** [comment]
> The proposed solution is to remove VORBIS VENDOR?

No the proposal is to hide VORBIS VENDOR from being shown as a "Custom Property" since it's supposed to be an encoded field of the codec used when the file is created. It isn't meant to be altered/deleted.

**Comment by nlogozzo** [comment]
> how about moving it to File Properties instead?

We could do this, but the fact is it shouldn't be considered a `Custom Property` as I said before it's not to be edited/altered.

Showing it under `File Properties` is kind of useless too since it's more for music players to learn the codec of the file and not something concerning the tag.

**Comment by kissthermite** [comment]
> Showing it under `File Properties` is kind of useless too since it's more for music players to learn the codec of the file and not something concerning the tag.

it's kinda useful for determining the origin of the file.

![name](https://media.discordapp.net/attachments/1139923418767175764/1166364869017223249/Screenshot_from_2023-10-24_20-17-21.png?ex=654a38ee&is=6537c3ee&hm=d4b5a062c57817800ba6224076f19142222e55d3c05d2e9124ee402d688cfd10&=&width=575&height=626)

like this file right here. And pretty much all of my flac wich i got from soulseek and deezer have identical VORBIS-VENDOR while the previous flac from this issue
have unique `VORBIS VENDOR` wich i guess it's because FFmpeg doing it's thing inside yt-dlp.

**Comment by fsobolev** [comment]
How about renaming "File properties" to "Read-only properties" and showing `VORBIS-VENDOR` and other things there if they are present in a file?

**Comment by kissthermite** [comment]
>which i guess it's because FFmpeg doing it's thing inside yt-dlp.

Forgot to mention but all five files on this issues screenshot are obtained from YouTube Music via Parabolic

**Comment by nlogozzo** [comment]
> How about renaming "File properties" to "Read-only properties" and showing `VORBIS-VENDOR` and other things there if they are present in a file?

I'll talk to ATL developer about creating read only additional properties

**Comment by nlogozzo** [comment]
@kissthermite Hi! Could you do me a favor and email me one of the `wav` files containing `info.ISFT` that isn't getting removed. My email is nlogozzo225@gmail.com . Thanks!

**Comment by kissthermite** [comment]
@nlogozzo Sure. Just did it few moments ago.

**Comment by nlogozzo** [comment]
Turns out these fields are removable but there were independent bugs affecting wav and vorbis files that prevented them from being removed. 

The developer of the tag library we use fixed these issues so I will update Tagger today with the fixes :)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.11.1

*Will be available through `flathub` within the hour!*
