### ISSUE TITLE
Allow "Tag to File Name" to create new folders

### ISSUE THREAD

**Issue by CharoSW** [NickvisionApps/Tagger#391]
Using the Flathub version I recently loaded up a folder in which several albums had just been jumbled up together. The Tag to file name option is one I had used before but because of these multiple albums I wanted to just split it up into individual folders.  Adding a forward slash only creates an underscore and not a new folder.  While I haven't checked I would assume that the WinUI version also has this issue, though with the backslash.  This would just be a really nice thing to have if you are dealing with multiple albums as I was

**Comment by nlogozzo** [comment]
> Adding a forward slash only creates an underscore and not a new folder

This is being `/` is not a valid file name character, so Tagger replaces it with `_`. Same wil happen on Windows with `\`.

I will look into using the directory separator within tag to file name as a way to make a new dir.

**Comment by kissthermite** [comment]
> I will look into using the directory separator within tag to file name as a way to make a new dir.

Yes please! also make it so that you can make a subdirectory as well e.g. /%artist%/%album%/file.flac

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.11.1

*Will be available through `flathub` within the hour!*
