### ISSUE TITLE
"Allow "Tag to File Name" to create new folders" does work but it will not work when "Limit File Name Characters" setting turned on.

### ISSUE THREAD

**Issue by kissthermite** [NickvisionApps/Tagger#395]
BTW it does work very well. Using custom format string `%albumartist%/%album%/ %artist% - %title%` will give this result.
![](https://media.discordapp.net/attachments/1139923418767175764/1170962541527187497/Screenshot_from_2023-11-06_12-45-29.png?ex=655af2d9&is=65487dd9&hm=e9abef38ce475b44f5a6d12219aea27e0f98206488786327dca2e1919b7957c7&=&width=575&height=626)

however when "Limit File Name Characters" setting turned on it will give this result.
![](https://media.discordapp.net/attachments/1139923418767175764/1170962541967593512/Screenshot_from_2023-11-06_12-46-23.png?ex=655af2d9&is=65487dd9&hm=0159f64b20a43e2640617353cb3e5d02f635ad7d2b29741822396a188ec0072f&=&width=575&height=626)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/2023.11.2
