### ISSUE TITLE
vorbis: allow multiple genre tags for flac

### ISSUE THREAD

**Issue by dfrein** [NickvisionApps/Tagger#402]
[vorbis format specification](https://xiph.org/vorbis/doc/v-comment.html) allows that tags / fields are not unique, but can be used more than one time, e.g. for artists or genres. This represents the recommended way to store multiple fields with multiple values. Currently, tagger (22.11.1) joins / concatenates such existing multiple tags in flac files into one field, which gives problems with some software. It would be good if tagger could support multiple fields with the same name, or at least does not touch existing multiple flac tags like artist or genre.

**Comment by dfrein** [comment]
Thank you for your explanation. In my case I tag the flac files myself this way, as this seems to be the recommended method for multiple genres for the logitech media server / the squeezebox streaming platform. And yes, tagger joins existing genre tags, separated with `;`.

**Comment by nlogozzo** [comment]
> In my case I tag the flac files myself this way, as this seems to be the recommended method for multiple genres for the logitech media server / the squeezebox streaming platform

Which is fine...

> And yes, tagger joins existing genre tags, separated with ;

So what's wrong with continuing to separate values of a field with `;`?

> which gives problems with some software

What are the problems seen in the other software? Tagger should display the multiple values as one separated by `;` and then when you add more values with `;`, in the backend it should separate them back out into a list and store it in the file appropriately.

**Comment by dfrein** [comment]
I had just fears that other software could be irritated by this, and sorting / filtering by genre (or artist) would not work as expected. But I just checked again with the most recent development version of logitech media server which (now?) seems also able to understand the delimiter `;`, so this seems not to be an issue for my use case, but rather a wish, to allow tagging with different software like kid3 in parallel.

**Comment by dfrein** [comment]
Thanks, there is mo real issue with kid3, it's just that I cannot use the pulldown list there for genres there in a meaningful way, as I first have to split up the existing genres again (but I have to check if there is some way to do that automatically in kid3). Because I have a list of the genres I usually use and I prefer it this way. Probably I should just change my workflow...
