### ISSUE TITLE
on Windows, it is impossible to update the application using the tools of the application itself

### ISSUE THREAD

**Issue by SokolovskyMaxim** [NickvisionApps/Tagger#403]
The application notifies when an update appears, but after clicking the update button, the application downloads the update, but does not install it. this kind of permission leads to nothing but an endless loading screen

**Comment by nlogozzo** [comment]
What version of the app are you using? (You can see from Help->About). Anything less than 2023.11.0 there was a bug in the update framework which caused this issue. Please go to the release page and download and install the latest version and after that the update framework will work for future versions.

**Comment by SokolovskyMaxim** [comment]
I have version 2023.11.1 installed. The current newest is 2023.11.2 and I can't install it. The application initially uses the network and CPU resources for the first couple of minutes, but then nothing happens. Endless loading screen and that's it

**Comment by nlogozzo** [comment]
> I have version 2023.11.1 installed. The current newest is 2023.11.2 and I can't install it. The application initially uses the network and CPU resources for the first couple of minutes, but then nothing happens. Endless loading screen and that's it

Sounds like it could be GitHub rate limiting...which was fixed in 2023.11.2

Try installing that manually from github releases and see if it loads without issue.
