### ISSUE TITLE
Collapse Artist Header in the Sidebar

### ISSUE THREAD

**Issue by ashenafiDL** [NickvisionApps/Tagger#415]
Description:
Currently, on the app's sidebar, there exists a hierarchy where artists are listed with their respective music underneath. However, there's a notable absence of a feature that allows collapsing the artist header, making navigation and content management more cumbersome.

Feature Request:
I propose the implementation of a feature that enables users to collapse the artist header in the sidebar. This collapsible functionality would streamline the interface, allowing users to expand or collapse artist headers, thereby improving accessibility and user experience.

**Comment by nlogozzo** [comment]
The sidebar is just a Gtk.ListBox with headers, it's not a Gtk.TreeView or anything like that that would allow collapsing headers, I don't think we should change it.
