### ISSUE TITLE
GNOME World

### ISSUE THREAD

**Issue by julianfairfax** [NickvisionApps/Tagger#421]
In addition to joining Circle, it would also be nice if the app's code were moved to [GNOME World](https://gitlab.gnome.org/World). GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

**Comment by nlogozzo** [comment]
I don't see us moving away from GitHub anytime soon....

Plus our apps aren't just for GNOME anymore so doesn't make sense to put them there.
