### ISSUE TITLE
Windows 11 won't start

### ISSUE THREAD

**Issue by utilop** [NickvisionApps/Tagger#433]
He writes exactly the same. Required "msix package version > = 4000.1010.1349.0" But when I install a newer version or 1.4.0 it still says the same
![image](https://github.com/NickvisionApps/Tagger/assets/77186394/c024dc10-1ab1-4aa3-b0ae-bad1b0153ab0)

**Comment by nlogozzo** [comment]
What happens if you re-install Tagger?

**Comment by mmvanheusden** [comment]
![image](https://github.com/NickvisionApps/Tagger/assets/50550545/c65cd33f-bcf9-41d5-b5ca-a201d6c00423)

Also happening for me.

**Comment by nlogozzo** [comment]
Will fix tomorrow, see #437

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2024.6.0
