### ISSUE TITLE
Requires  Windows App SDK 1.4

### ISSUE THREAD

**Issue by OrloDavid** [NickvisionApps/Tagger#437]
Missing Win App SDK 1.4
Redistributable
https://aka.ms/windowsappsdk/1.4/1.4.240512000/Microsoft.WindowsAppRuntime.Redist.1.4.zip

And no start menu entries for this or Parabolic? 
Maybe give Inno-Setup compiler a try, I've used it in the past and it worked well
https://jrsoftware.org/isdl.php

**Comment by nlogozzo** [comment]
> And no start menu entries for this or Parabolic?
Maybe give Inno-Setup compiler a try, I've used it in the past and it worked well

Inno-Setup is exactly what we use to build the Windows installers...and the menu entries show up correctly for me. Try logging on and off again?

I will update all the dependencies tomorrow and release an update to fix this issue.

**Comment by OrloDavid** [comment]
DM Me, I found something Parabolic does and I'm unsure if your aware of it. Kind of found it by accident myself. 
Yes the start menu entries are showing up now, which was slightly related to parabolic as well.

**Comment by nlogozzo** [comment]
> DM Me

You can message me on Matrix: `@nlogozzo:matrix.org`

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2024.6.0
