### ISSUE TITLE
Fix corrupt tags by hand

### ISSUE THREAD

**Issue by Louis99999** [NickvisionApps/Tagger#441]
Is there any way to do that? I've got about dozen files that Tagger says have corrupted tags and so won't list. As near as I can tell, they're no different from the rest. What should I be looking for?

By the way, Tagger is amazing. My music has been screwed up for at least 15 years, and I now see the light at the tunnel.

**Comment by nlogozzo** [comment]
https://htmlpreview.github.io/?https://raw.githubusercontent.com/NickvisionApps/Tagger/main/NickvisionTagger.Shared/Docs/html/C/corrupted.html

This is Tagger's documentation page in which you can read more about corrupted tags.

**Comment by Louis99999** [comment]
Thank you.. don't know how I missed that.
