### ISSUE TITLE
Tagger not responding

### ISSUE THREAD

**Issue by Polleke55** [NickvisionApps/Tagger#446]
When Tagger is launching on Xubuntu 22.0.3 and Xubuntu 24.0.4.3 it's not responding. Nothing happens.
The tagger folders are empyty. 
Removed the app and re-install have no effect. Tagger seems to bee dead.
Launching it from the terminal: Content snap command-chain for /snap/tagger/464/gpu-2404/bin/gpu-2404-provider-wrapper not found: ensure slot is connected
Is there an solution?

**Comment by nlogozzo** [comment]
@soumyaDghosh sounds like a snap issue

**Comment by Polleke55** [comment]
The other programm's (WhatSie, Freac) in the snap folder just working fine.

**Comment by nlogozzo** [comment]
> The other programm's (WhatSie, Freac) in the snap folder just working fine.

Each snap program is isolated. So it's a problem with the specific Tagger snap package.

If you use Flatpak, Tagger is available on Flatpak you can try that.

**Comment by soumyaDghosh** [comment]
I see, I had this in my local machine also, but I thought that it's only my issue, as I had it from long time, before we got auto-connection. Wait a min, I'll post about it in the forum.

**Comment by soumyaDghosh** [comment]
@Polleke55 can you refresh and check?

**Comment by Polleke55** [comment]
For various reasons I reinstalled xubuntu and it fixed the problem. Thank you very much for your response.
