### ISSUE TITLE
Existing embedded artwork not loading

### ISSUE THREAD

**Issue by shoveln** [NickvisionApps/Tagger#70]
When I open an album or song with existing embedded artwork (which shows up in music players on multiple operating systems, so I know it exists), it doesn't render. Selecting every song in an album or just a single song both don't show the artwork. If I use the file picker and upload new album art, that does render. This makes it difficult to know if an album already has existing artwork. 

OS: Fedora 37
GNOME Version: 43.1

**Comment by nlogozzo** [comment]
What tagging software did you previously use? I have to see how they stored album art into the file.

Also what file type are you using?

**Comment by shoveln** [comment]
I've used Puddletag in the past, but most of my library now just uses the tags/artwork supplied by Deezer/Deemix. Puddletag has recognized the artwork from Deemix consistently in my experience. 

I am using FLAC files, haven't tested with other file types. The embedded art is stored as a PNG based on the settings I use for Deemix. All of the other tags such as artist, track number, etc load correctly.

**Comment by nlogozzo** [comment]
I'll take a look at how I handle Album Art in FLAC

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.7.0-beta1
