### ISSUE TITLE
Double digit track number

### ISSUE THREAD

**Issue by drakkar1969** [NickvisionApps/Tagger#74]
I usually use double digit track numbers when tagging, to ensure proper filename sorting when renaming files from tags.
Even if I insert a 0-padded double digit track number (e.g. `09`), Tagger saves it as a single digit (`9`).

Any chance this behavior could be changed?

Thanks for the great program btw

**Comment by nlogozzo** [comment]
Yeah I will add an extra 0 padding to single digit nunbers when they are displayed.

**Comment by drakkar1969** [comment]
Thanks!

**Comment by psychonaut** [comment]
... and please replace dash with dot (or add possibility for creating your own format) i.e.

01. <track>

not 

01- <track>

**Comment by nlogozzo** [comment]
> ... and please replace dash with dot (or add possibility for creating your own format) i.e.

I would love to make it where you could define your own format!

Could you create a separate issue to track? :)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.7.0-beta1
