### ISSUE TITLE
Add possibility for creating your own format of track name

### ISSUE THREAD

**Issue by psychonaut** [NickvisionApps/Tagger#76]
Currently once can choose from a fixed set of formats but we have our own preferences for naming music files. It would be great if Tagger allowed that.

**Comment by Vinnl** [comment]
Is this issue about converting file names to tags? Because if so, yes, I've got file names in the format `%track%. %artist% - %title%`, but cannot currently convert those to tags with Tagger.

If this issue is about something else, let me know and I'll file a separate issue.

**Comment by nlogozzo** [comment]
Yes this issue applies to filename to tag conversion.  Hoping to get it implemented for the next release :)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.7.1-rc1
