### ISSUE TITLE
Pressing Enter in the convert filename to tag popup activates Cancel

### ISSUE THREAD

**Issue by mgedmin** [NickvisionApps/Tagger#85]
Steps to reproduce:

1. select an mp3 file with a filename Artist - Title.mp3 and with no ID3 tag
2. press Ctrl+F to Convert Filename to Tag
3. press Enter

Expectation:

- the Ok button (highlighted in blue) gets triggered and empty artist/title metadata fields get filled in

Actual results:

- the Cancel button gets triggered and the popup is dismissed without filling anything in

Version: 2022.11.2 from Flathub

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.7.0-beta1
