### ISSUE TITLE
Music file album art deleted downloading metadata

### ISSUE THREAD

**Issue by Nokse22** [NickvisionApps/Tagger#86]
Great app.
I think it could be useful a separate toggle to decide if the album art is deleted when downloading the metadata but there isn't an album cover on the website.
Because sometimes the name, artist... are wrong, but present and there is an album cover and if I disable "Overwite tag with musicbrainz" nothing is written

**Comment by nlogozzo** [comment]
I'll probably make it where, If you download metadata it will only effect your album art if it's empty. Meaning if you set one, it won't overwrite it.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.7.0-beta1
