### ISSUE TITLE
Design changes proposals

### ISSUE THREAD

**Issue by fsobolev** [NickvisionApps/Tagger#91]
Some suggestions to improve Tagger interface.

- [x] To achieve adaptiveness add bottom bar, move Web Services, Tag Actions and Apply buttons there, and also add a toggle button to control flap.
- [x] Hide rigth pane for empty folders.
- [x] Show StatusPage in right pane when nothing is selected, instead of showing empty tags entries.
- [x] Move advanced search help to yelp docs.
- [x] Avoid using EntryRow for read-only file properties: ActionRow with label in suffix can be used for duration and file size, and for fingerprint we could not show fingerprint but add a button to copy it to clipboard.
- [x] Maybe move search entry to bottom bar? Or at least add separator between it and the files list.
- [x] Improve album art, to show that the user can click to change it. Change cursor on hover, and add little edit icon in the corner of image.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.7.1-beta2
